### ISSUE TITLE
The following error will appear in the card configuration. How to solve it?

### ISSUE THREAD

**Issue by a120578270** [jcwillox/lovelace-canary#11]
- entity: binary_sensor.motion_sensor_158d000222be72
    secondary_info:
     entity: sensor.da_men_shi_jian_chuo
     prefix: "The average fuel price is "
     postfix: " ¢/L"  

The following error will appear in the card configuration. How to solve it?

UI editor is not supported for this config:
The value of "entities.1" is not supported by the UI editor, we support "Object<{entity,name,icon,image,secondary_info,format,state_color,tap_action,hold_action,double_tap_action}> | string | Object<{type,name,action_name,tap_action,hold_action,double_tap_action}> | Object<{type,view,dashboard,name,icon,hide_if_unavailable}> | Object<{type,row,conditions}> | Object<{type,style}> | Object<{type,label}> | Object<{type,url,name,icon}> | Object<{type,entities}> | Object<{type,entity,attribute,prefix,suffix,name}> | Object<{type,name,service,icon,action_name,service_data}>" but received "{"entity":"binary_sensor.motion_sensor_158d000222be72","secondary_info":{"entity":"sensor.da_men_shi_jian_chuo","prefix":"The average fuel price is ","postfix":" ¢/L"}}".You can still edit your config in YAML.

**Comment by jcwillox** [comment]
Yeah, that's just Home Assistant being Home Assistant, the UI editor stops working pretty quickly when you start using complex YAML configs and custom plugins.

The "error" is really just an informational message caused when Lovelace sees that `secondary_info` is an object and not a string like it expects.

There isn't a solution to this, other than not using object templates and using string-based templates, e.g. [Jinja](https://github.com/jcwillox/lovelace-canary/wiki/Generic-Entity-Row#jinja-templates) or [Thomas Lovén's templates](https://github.com/thomasloven/hass-config/wiki/Mod-plugin-templates).
