### ISSUE TITLE
issue with secondary info for cover entity card

### ISSUE THREAD

**Issue by wivaku** [jcwillox/lovelace-canary#12]
Canary causes an issue with entity card secondary info for Hunter Douglas cover.  
https://github.com/home-assistant/frontend/issues/8199

Is there a way to select the card's default `secondary_info` instead of the Canary one?

**Comment by jcwillox** [comment]
Yes check out the [disabling extensions](https://github.com/jcwillox/lovelace-canary/wiki/Disabling-Extensions) wiki page, this is actually a duplicate of #10.
This is expected and intended as canary overrides the default behaviour of the `secondary_info` option, and I can't add exceptions for every custom card that uses the secondary info option, adding `disable_canary: secondary_info` to your cards config will disable canary.

**Comment by wivaku** [comment]
wonderful, thanks!

**Comment by jcwillox** [comment]
I've added `position` and the other new builtin secondary info to the exclusions list in [0.3.2](https://github.com/jcwillox/lovelace-canary/releases/tag/0.3.2) you should no longer need to use `disable_canary: secondary_info`. In hindsight, I probably should've called it `canary_secondary_info` to avoid clashes with internal and custom components 🤷
