### ISSUE TITLE
Problem with changing div.card-header padding of vertical-stack with in_card: true

### ISSUE THREAD

**Issue by bieniu** [jcwillox/lovelace-canary#6]
I use `Canary` to add `title` to the `simple-weather-card`:
```
         - type: vertical-stack
            in_card: true
            title: "Weather"
            style: |
              div.card-header {
                padding-bottom: 0px;
              }
            cards:
              - type: custom:simple-weather-card
                entity: weather.dom
                name: " "
                primary_info:
                  - humidity
                  - precipitation_probability
                secondary_info:
                  - pressure
```
and I have a problem with changing `padding-bottom` of `div.card-header`. It doesn't work at all. Could you tell me where I'm making a mistake?

**Comment by jcwillox** [comment]
Sorry for the delay, I'm not sure card-mod works on `vertical-stack` cards, does it work without the `in_card: true`.

Other ways to produce that effect would be to use card-mod's `mod-card` or to set a negative margin on the first card, e.g.

```yaml
type: custom:simple-weather-card
canary_style:
  margin-top: '-16px'
```

**Comment by bieniu** [comment]
It works! Thanks a lot.
